name: Cron Task on Commit

on:
  push:
    branches:
      - main
    paths:
      - 'uploads/**'

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Process added files
      run: |
        python3 main.py

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update levels.json file"
        branch: "update-levels"
        delete-branch: true
        title: "Automated Update: levels.json"
        body: "This pull request updates the levels.json file based on new uploads."
        labels: "automated update"
        reviewers: "OmgRod"

    - name: Display PR Details
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
