name: Update Levels and Create Pull Request

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config user.name "OmgRod"
          git config user.email "89850217+OmgRod@users.noreply.github.com"

      - name: Fetch and Create Branch from main
        run: |
          git fetch origin
          git checkout -b update-levels origin/main

      - name: Modify levels.json
        run: |
          echo '{"level": "1", "name": "Level One"}' > levels.json
          cat levels.json  # This is just to confirm the change (debugging step)

      - name: Commit changes to levels.json
        run: |
          git add levels.json
          git status  # Check the status to see what has been added
          git commit -m "Update levels.json file"
          git log --oneline  # Check the last commit to ensure it's there

      - name: Fetch remote update-levels branch
        run: |
          git fetch origin update-levels

      - name: Merge remote update-levels
        run: |
          git merge origin/update-levels --no-edit

      - name: Push changes to update-levels
        run: |
          git push origin update-levels

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update levels.json"
          body: "This PR updates the levels.json file."
          base: main
          branch: update-levels
